### PR TITLE
[BUGFIX] Detected current page right for pages

### PR DESCRIPTION
**Pull request by Mabahe**
Resolves: #327

### CODE REVIEW

**Comment by calien666** [comment]
Duplicates #329

**Comment by Mabahe** [comment]
Nope, is for branch 3.0! We still use this currently.

**Comment by calien666** [comment]
Ah, yes, sorry. I didn't see.

**Review by calien666 — APPROVED** [review]

**Comment by Mabahe** [comment]
thx

**Review by sbuerk — APPROVED** [review]

**Pull request merged**
