### PR TITLE
[FEATURE] Fix #39: add glossary support

### LINKED ISSUE #39: Feature request: Add support for DeepL glossary
The DeepL glossary is also supported within the API since August 24, 2021.

> The glossary functions allow you to create, inspect and delete glossaries. It is available at https://api.deepl.com/v2/glossaries. Glossaries created with the glossary function can be used in translate requests by specifying the glossary_id parameter.

This may improve the output because a more domain specific set of terms is used. For example, for the university we use a term library for English / German which is regularly updated.

---

* glossary documentation: https://www.deepl.com/docs-api/managing-glossaries/
* [Announcing Glossary Support for the DeepL API](https://www.deepl.com/en/blog/announcing-glossary-support-for-deepl-api)
* First blog entry for glossary support: https://www.deepl.com/en/blog/20200506

### PR DESCRIPTION
**Pull request by dmitryd**
#39 

Also minor clean up.

### CODE REVIEW

**Comment by NarkNiro** [comment]
Hello @dmitryd thanks for your pull request, the idea is not bad. We would prefer a different approach here. So that also TYPO3 backend users can maintain this glossary via TCA tables.

Therefore I will have to reject the pull request.

**Comment by dmitryd** [comment]
@NarkNiro Are you sure? TCA defines how forms are rendered in the Backend by TYPO3. This not really suitable for anything like configuring glossaries.

If you mean storing glossaries in the database and editing them in Backend, this would not be the most effective choice because you will need a whole new database table for less than ten entries, typically even a single entry. This is too much overhead. Glossaries are usually uploaded and not changed too often. So setting them via database will only add extra calls to the database for a potentially single record. TS is already loaded at that point, so there is not overhead of any kind.

Also it will cause questions of who needs access and where these table has to be stored, which is extra headache.

**Comment by dmitryd** [comment]
@NarkNiro I see the feature is there now but there is no any kind of documentation how to use it. In my implementation it was automatic: if the glossary is there, it was used automatically.

In the current implementation I see some kind of complex magic with extbase model, database tables, sync buttons, etc. However I do not see any button anywhere in the backend, I cannot sync anything, no records are created. I have uploaded glossaries via deepl web site but nothing is used in TYPO3. This is so complicated! How can this actually be used? We have about 400 web sites that need to use the glossary. I hope I do not have to upload it with some console command all 400 times for each web site?..

**Comment by sypets** [comment]
>  I have uploaded glossaries via deepl web site but nothing is used in TYPO3. 

!!!

**Glossaries created via the DeepL API are distinct from glossaries created via the DeepL website and DeepL apps**. This means API glossaries cannot be used on the website and vice versa.

https://www.deepl.com/docs-api/glossaries/get-glossary-entries/

Tipp: 

* You can use the command line tools to list the glossaries which are available in Deepl (you can maintain several glossaries in DeepL). 

* deepl:glossary:cleanup
* deepl:glossary:list

Last time I checked, the glossary created in TYPO3 had a distinct name.

**Comment by sypets** [comment]
Also, I partially agree. (However I have not looked at the latest version so not so familiar with latest developments)

Related: #119 

Uploading a glossary to DeepL (via the API) is pretty simple, see https://packagist.org/packages/deeplcom/deepl-php

What is not so simple is maintaining it. I would also like more flexibility here, so it is possible to maintain the glossary outside of TYPO3. with a separate extension for the glossary so you can choose to maintain it in TYPO3 or maintain it elsewhere.

**Comment by dmitryd** [comment]
We also have a very simple command to list, delete and upload glossaries from a csv file. The whole code is 427 lines with comments and phpdocs. So here is how we do it:

- upload the glossary using a console command
- it becomes automatically available anywhere where this deepl key is used (on every web site)

The command was not in my MR unfortunately.

**Comment by dmitryd** [comment]
For maintaining: our command can delete glossaries by id.

**Comment by sypets** [comment]
> it becomes automatically available anywhere where this deepl key is used
exactly!

**Comment by dmitryd** [comment]
In my MR I imagined the following workflow within the organisation with a single of multiple web sites:

- Somebody in the company creates a glossary in a readable format, like XLS
- It is verified by some other people
- It is given to IT guys, who convert it to CVS or TSV
- IT guys upload the new glossary to the site using the console command
- Webdevs change glossary ID to a new one in TypoScript
- Webdevs deploy the change to production
- IT guys remove the old glossary from deepl using the console command
- Sites start to use the new glossary automatically after deployment

This is very smooth approach, which does require any sync or button press from editors. All management of glossaries happen by clearly defined roles and responsible people.

**Comment by calien666** [comment]
@dmitryd This seems to be a nice and useful feature. Let's have some discussion, how we can implement this. Currently, I guess, it would be nice, to have some points where to manipulate the glossary, for example an event. So a separate extension can register to and no glossary is needed inside TYPO3. This is, what you want to have? In this case, we should prepare this for next release.
After this PR is closed, feel tree to start a feature issue and add it to v4 milestone.

**Pull request closed without merging**
