### PR TITLE
[FEATURE] Deepl - Support for more languages

### PR DESCRIPTION
**Pull request by ayacoo**
Related #23

### CODE REVIEW

**Comment by sypets** [comment]
Should probably also change the text for translation button:

"Deepl service supports translation to and from English, French, German, Spanish, Italian, Dutch, and Polish languages.Other languages will be ignored and will default to the normal translate operation of TYPO3."

https://github.com/web-vision/wv_deepltranslate/blob/master/Resources/Private/Language/locallang.xlf

**Comment by ayacoo** [comment]
Thanks for your feedback. I have adjusted the locallang a bit, but kept the text more general, because otherwise I think it will be too long if we list every language.

**Review by sypets — APPROVED** [review]

**Comment by NairCoder** [comment]
Hello @ayacoo Just noticed that in the list, 'PT' is duplicated.

**Comment by NairCoder** [comment]
Merged to master by fixing some minor stuff and hence closing this PR.
Thanks @ayacoo and @sypets

**Pull request closed without merging**
